# Generated by Django 4.1.3 on 2023-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=10)),
                ('meeting_id', models.CharField(max_length=20)),
                ('passcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='meetingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
            ],
        ),
    ]
