# Generated by Django 4.1.3 on 2023-01-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_createmeeting_meetingdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createmeeting',
            old_name='passcode',
            new_name='agenda',
        ),
        migrations.RemoveField(
            model_name='createmeeting',
            name='meeting_id',
        ),
    ]
