# Generated by Django 4.1.3 on 2023-01-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_passcode_createmeeting_agenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmeeting',
            name='agenda',
        ),
        migrations.AddField(
            model_name='createmeeting',
            name='start_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
