# Generated by Django 4.1.3 on 2023-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_createmeeting_agenda_createmeeting_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmeeting',
            name='date',
        ),
        migrations.AddField(
            model_name='meetingdetail',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingdetail',
            name='meeting_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingdetail',
            name='passcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
