# Generated by Django 4.1.3 on 2023-01-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_createmeeting_date_meetingdetail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmeeting',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meetingdetail'),
        ),
    ]
