# Generated by Django 4.1.3 on 2023-01-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_createmeeting_meeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meetingDetail',
            new_name='meetDetail',
        ),
        migrations.RemoveField(
            model_name='createmeeting',
            name='meeting',
        ),
    ]
