# Generated by Django 4.1.3 on 2023-01-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_meetingdetail_meetdetail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meetDetail',
        ),
        migrations.AddField(
            model_name='createmeeting',
            name='meeting_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createmeeting',
            name='passcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createmeeting',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
