# Generated by Django 4.1.3 on 2023-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_createmeeting_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmeeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='meeting_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='passcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
