# Generated by Django 4.1.3 on 2023-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmeeting',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
