# Generated by Django 4.1.3 on 2023-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_detail_createmeeting_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createmeeting',
            old_name='time',
            new_name='End_time',
        ),
        migrations.AlterField(
            model_name='createmeeting',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
