# Generated by Django 4.1.3 on 2023-02-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_time_createmeeting_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmeeting',
            name='End_time',
        ),
    ]
