# Generated by Django 4.1.3 on 2023-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_createmeeting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmeeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
